services:
  db:
    image: postgres:15
    container_name: auth_db
    restart: unless-stopped
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  auth_service:
    build: .
    container_name: auth_service
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./:/app 

volumes:
  postgres_data:
